version: '3.8'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor-amd64:v0.47.2  # gcr repository to fetch latets img
    user: "1000:122"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro  # disk metrics
    ports:
      - "8081:8080"
    privileged: true  # This gives cAdvisor access to the host system
    restart: always
  
  nodeexporter:
    image: prom/node-exporter:v1.7.0  # latest version 
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    restart: unless-stopped