global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'jenkins-data'
    static_configs:
      - targets: ['13.48.223.124:8080']
    metrics_path: '/prometheus'

  - job_name: 'the-room-cadvisor'
    static_configs:
      - targets: ['51.20.13.144:8081']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['51.20.13.144:9100']
    metrics_path: '/metrics'
