---
- name: Install Docker, Docker Credential Helper, and Deploy Jenkins on EC2
  hosts: docker
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker.io
      apt:
        name: docker.io
        state: present

    - name: Start Docker and enable on boot
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install pass, gnupg2, and rng-tools
      apt:
        name:
          - pass
          - gnupg2
          - rng-tools
        state: present

    - name: Generate GPG key batch file
      become: yes
      become_user: ubuntu
      copy:
        dest: /home/ubuntu/gpg_key_batch
        content: |
          %echo Generating a basic OpenPGP key
          Key-Type: default
          Subkey-Type: default
          Name-Real: jenkins
          Name-Comment: with no passphrase
          Name-Email: dariusbyckovskij@gmail.com
          Expire-Date: 0
          %no-protection
          %commit
          %echo done
        mode: '0600'
        owner: ubuntu
        group: ubuntu

    - name: Generate GPG key for ubuntu
      become: yes
      become_user: ubuntu
      command: gpg --batch --gen-key /home/ubuntu/gpg_key_batch
      args:
        creates: /home/ubuntu/.gnupg/pubring.kbx
      environment:
        GNUPGHOME: /home/ubuntu/.gnupg
      register: gpg_key_creation
      ignore_errors: yes

    - name: Debug GPG Key Creation
      debug:
        var: gpg_key_creation

    - name: Get GPG Key ID
      become: yes
      become_user: ubuntu
      shell: >
        gpg --list-keys --with-colons --fingerprint | 
        grep '^fpr' | 
        head -n1 | 
        awk -F: '{print $10}'
      args:
        executable: /bin/bash
      register: gpg_key_id
      changed_when: false

    - name: Debug GPG Key ID
      debug:
        var: gpg_key_id.stdout


    - name: Initialize pass for user ubuntu
      become: yes
      become_user: ubuntu
      command: pass init "{{ gpg_key_id.stdout }}"
      args:
        creates: /home/ubuntu/.password-store

    - name: Download Docker Credential Helper
      get_url:
        url: https://github.com/docker/docker-credential-helpers/releases/download/v0.8.1/docker-credential-pass-v0.8.1.linux-amd64
        dest: /tmp/docker-credential-pass
        mode: '0755'

    - name: Move Docker Credential Helper to /usr/local/bin/
      command: mv /tmp/docker-credential-pass /usr/local/bin/docker-credential-pass
      args:
        creates: /usr/local/bin/docker-credential-pass

    - name: Set execute permission for Docker Credential Helper
      file:
        path: /usr/local/bin/docker-credential-pass
        mode: '0755'

    - name: Set up Docker Credential Helper for user ubuntu
      become: yes
      become_user: ubuntu
      block:
        - name: Ensure .docker directory exists for user ubuntu
          file:
            path: /home/ubuntu/.docker
            state: directory
            mode: '0700'
            owner: ubuntu
            group: ubuntu

        - name: Configure Docker to use Credential Helper for user ubuntu
          copy:
            dest: /home/ubuntu/.docker/config.json
            content: |
              {
                "credsStore": "pass"
              }
            mode: '0600'
            owner: ubuntu
            group: ubuntu

