# version: '3.8'

# services:
#   jenkins:
#     image: dariusby/jenkins-w-docker:updated
#     ports:
#       - "8080:8080"
#       - "50000:50000"
#     restart: always
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock


version: '3.8'
services:
  jenkins:
    image: dariusby/jenkins-w-docker:5
    container_name: jenkins
    user: "1000:999"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/jenkins_data:/var/jenkins_home
    restart: always
