---
- name: Start EC2 instances
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Run EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        region: eu-north-1
        key_name: "k8s"
        vpc_subnet_id: subnet-08d67964171eeb5b3
        instance_type: t3.micro
        security_group: ssh_icmp
        network:
          private_ip_address: "{{ item.private_ip }}"
        image_id: ami-0fe8bec493a81c7da
        user_data: |
          #!/bin/bash
          hostnamectl set-hostname {{ item.name }}
        tags:
          Environment: Testing
      loop:
        - { name: "master", private_ip: "172.31.0.10" }
        - { name: "swarm", private_ip: "172.31.0.11" }
